### ISSUE TITLE
:ensure t

### ISSUE THREAD

**Issue by yenda** [ghoseb/dotemacs#24]
Is there a particular reason for you not to use the :ensure t flag with use-package ? I might be missing something but it will make the use of cask unnecessary.

**Comment by ghoseb** [comment]
@yenda Good idea, but I don't use `:ensure` primarily because in some cases I would like to pin certain packages to some specific versions. Since MELPA etc don't do versioning (in conjunction with `use-package` at least) I use cask to pin versions to the SHA-1, etc.

This allows me to keep my config `reproducible`.
